name: Collect New Books

on:
  schedule:
    - cron: "0 */12 * * *"

jobs:
  collect-data:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - uses: pnpm/action-setup@v2
      with:
        version: 8
      
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Install Dependencies
      run: pnpm install --frozen-lockfile

    - name: Collect Data
      run: |
        pnpm run cmd collect \
          --site acorn \
          --site bjpublic \
          --site easyspub \
          --site gilbut \
          --site hanbit \
          --site insight \
          --site wikibook

    - name: Copy Outputs
      run: cp -r dist/* public/

    - name: Commit Changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: 'chore: update feeds'
        commit_options: '--no-verify --signoff'
        file_pattern: public/*
