name: Collect New Books

on:
  schedule:
    - cron: "0 */12 * * *"

jobs:
  collect-data:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@main

      - uses: pnpm/action-setup@master

      - name: Use Node.js 20.x
        uses: actions/setup-node@main
        with:
          node-version: 20.x

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Collect Data
        run: |
          pnpm run cmd collect \
            --site acorn \
            --site bjpublic \
            --site easyspub \
            --site gilbut \
            --site hanbit \
            --site insight \
            --site wikibook

      - name: Copy Outputs
        run: cp -r dist/* public/

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: update feeds"
          commit_options: "--no-verify --signoff"
          file_pattern: public/*
